/**
 * DO NOT EDIT
 *
 * This file is automatically generated (as a pre-commit step)
 */

export = {
  plugins: ['ngrx'],
  rules: {
    'ngrx/no-dispatch-in-effects': 'warn',
    'ngrx/no-effect-decorator-and-creator': 'error',
    'ngrx/no-effect-decorator': 'error',
    'ngrx/no-effects-in-providers': 'error',
    'ngrx/no-multiple-actions-in-effects': 'error',
    'ngrx/prefer-concat-latest-from': 'warn',
    'ngrx/prefer-effect-callback-in-block-statement': 'error',
    'ngrx/use-effects-lifecycle-interface': 'warn',
  },
}
