import { writeFileSync } from 'fs'
import { join } from 'path'
import { format, resolveConfig } from 'prettier'
import { rules } from '../src/rules'
import { RuleModule } from '../src/utils/types'

const prettierConfig = resolveConfig.sync(__dirname)

const RULE_NAME_PREFIX = 'ngrx/'
const CONFIG_DIRECTORY = './src/configs/'

const getRules = (predicate: (rule: RuleModule) => boolean) =>
  Object.entries(rules).reduce((rules, [ruleName, rule]) => {
    if (predicate(rule)) {
      rules[`${RULE_NAME_PREFIX}${ruleName}`] =
        rule.meta.docs?.recommended || 'warn'
    }
    return rules
  }, {})

const rxjsRules = {
  'rxjs/no-cyclic-action': 'error',
  'rxjs/no-unsafe-catch': 'error',
  'rxjs/no-unsafe-first': 'error',
  'rxjs/no-unsafe-switchmap': 'error',
}

writeConfig('recommended', {
  ...getRules((rule) => !!rule.meta.docs?.recommended),
  ...rxjsRules,
})

writeConfig('all', {
  ...getRules((_) => true),
  ...rxjsRules,
})

writeConfig(
  'store',
  {
    ...getRules((rule) => rule.meta.module === 'store'),
  },
  ['ngrx'],
)

writeConfig(
  'effects',
  {
    ...getRules((rule) => rule.meta.module === 'effects'),
  },
  ['ngrx'],
)

function writeConfig(
  configName: 'recommended' | 'all' | 'store' | 'effects',
  configRules: Record<string, string>,
  plugins = ['ngrx', 'rxjs'],
) {
  const code = `
/**
 * DO NOT EDIT
 *
 * This file is automatically generated (as a pre-commit step)
 */

export = {
  plugins: ${JSON.stringify(plugins)},
  rules: ${JSON.stringify(configRules)},
}
`
  const config = format(code, {
    parser: 'typescript',
    ...prettierConfig,
  })
  writeFileSync(join(CONFIG_DIRECTORY, `${configName}.ts`), config)
}
