name: 'Maintenance'
on:
  # So that PRs touching the same files as the push are updated
  push:
    branches:
      - main
  # So that the `dirtyLabel` is removed if conflicts are resolved
  # Could put too much strain on rate limit
  # If we hit the rate limit too often remove this event
  pull_request_target:
    branches:
      - main
    types: [synchronize]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.actor }}"
      - name: check if prs are dirty
        uses: eps1lon/actions-label-merge-conflict@releases/2.x
        with:
          dirtyLabel: 'merge-conflict'
          removeOnDirtyLabel: 'Ready to ship'
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          retryAfter: 130
          retryMax: 10
