name: release

on:
  push:
    branches:
      - master

jobs:
  release:
    if: github.repository == 'timdeschryver/eslint-plugin-ngrx'
    timeout-minutes: 5
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install
        run: npm ci
      - name: build
        run: npm run build
      - name: test
        run: npm run test -- --ci
        env:
          CI: true
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
